# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: ZaCT-Media/zact-starter-v1
  branch: main
  identity_url: https://auth.decapbridge.com/sites/e7d51885-0a69-4e61-aa93-aa1d80a20dec
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://www.zactmedia.co.uk/assets/images/logo.svg

# Add site links in DecapCMS (optional)
site_url: https://zact-starter-v1.pages.dev